#ORDER BY AND LIMIT
SELECT * FROM students ORDER BY cgpa ASC;
SELECT * FROM students ORDER BY cgpa DESC;
SELECT * FROM students ORDER BY age DESC;
SELECT * FROM students ORDER BY branch;
SELECT * FROM students ORDER BY cgpa DESC,age ASC;
SELECT * FROM students ORDER BY cgpa DESC LIMIT 1;
SELECT * FROM students ORDER BY cgpa ASC LIMIT 1;
SELECT * FROM students ORDER BY cgpa DESC LIMIT 3;
SELECT * FROM students ORDER BY age ASC LIMIT 2;
SELECT * FROM students WHERE branch='AIML' ORDER BY cgpa DESC LIMIT 5;
